# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - refs/tags/v*

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      npm install
      npm run compile
      echo ">>> Publish"
      npm run deploy
    displayName: Publish
    env:
      VSCE_PAT: $(VSCE_PAT)
